### ISSUE TITLE
Crash on 1.19.2 (Forge 43.2.4) - Breezy 1.0.4 - Multiplayer

### ISSUE THREAD

**Issue by DeltaWolf7** [Coda1552/Breezy#9]
When connecting to a MP server with Breezy installed the following error is seen on the client side.

`java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.19.2 of loader 'TRANSFORMER' @63636de0)
	at coda.breezy.Breezy.lambda$resetWindDirection$1(Breezy.java:68) ~[breezy-1.19.2-1.0.4.jar%23593!/:1.19.2-1.0.4] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at coda.breezy.Breezy.resetWindDirection(Breezy.java:67) ~[breezy-1.19.2-1.0.4.jar%23593!/:1.19.2-1.0.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:815) ~[forge-1.19.2-43.2.4-universal.jar%23956!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1815) ~[client-1.19.2-20220805.130853-srg.jar%23951!/:?] `

`-- Head --
Thread: Render thread
Stacktrace:
	at coda.breezy.Breezy.lambda$resetWindDirection$1(Breezy.java:68) ~[breezy-1.19.2-1.0.4.jar%23593!/:1.19.2-1.0.4] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at coda.breezy.Breezy.resetWindDirection(Breezy.java:67) ~[breezy-1.19.2-1.0.4.jar%23593!/:1.19.2-1.0.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:815) ~[forge-1.19.2-43.2.4-universal.jar%23956!/:?] {re:mixin,re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['DeltaWolf7'/5074, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 1024, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:`

**Comment by noncom** [comment]
Just got the same crash right now.
What can I say, it looks like the mod thinks that it always runs on the server.
It just casts the level without any checks: https://github.com/Coda1552/Breezy/blob/b809462faac276ef9c42a0e611d1d8eaee105c37/src/main/java/coda/breezy/Breezy.java#L88

Idk but this probably has to be guarded with the is-server check or something.

**Comment by Coda1552** [comment]
Should be fixed in the next version, if you still experience this crash feel free to reopen this issue.
